title: 'GSoC 2020 Tracker'

header_pages:
  - about.md
  - language.md

style: dark

footer: 'follow me on <a href="https://github.com/VedantParanjape">github</a>'

# Build settings
markdown: kramdown
theme: jekyll-theme-console
